version: '2'
services:
  gcf-local:
    container_name: gcf-local
    build:
      dockerfile: GCFLocal.Dockerfile
      context: .
    links:
      - test-server
  smoke-tests:
    container_name: transcoder-smoketests
    build: 
      dockerfile: SmokeTests.Dockerfile
      context: .
    links:
      - gcf-local
  test-server:
    container_name: transcoder-testserver
    build: 
      dockerfile: TestServer.Dockerfile
      context: .
